### ISSUE TITLE
Support for iOS7 / Older Androids

### ISSUE THREAD

**Issue by RobertoGonzalez** [Aerolab/midnight.js#1]
Older iOS versions update scrollTop every once in a while, which causes quite a few issues. While there's a workaround (add a wrapper for the body and using that instead), it'd be better to just disable it due to poor performance.

**Comment by tomByrer** [comment]
How old is "older"?
I think [fullpage.js](https://github.com/alvarotrigo/fullPage.js/issues?q=is%3Aissue+ios) has & had many iOS issues, perhaps you can learn some new tricks there?
