### ISSUE TITLE
author = "Aerolab" ?

### ISSUE THREAD

**Issue by tomByrer** [Aerolab/midnight.js#11]
Glad you're using [Releases](https://github.com/Aerolab/midnight.js/releases/)!  Makes it easier for jsDelivr CDN to pull updates automatically  :)
While setting up your `info.ini`, it [was noticed](https://github.com/jsdelivr/jsdelivr/pull/1855#issuecomment-57071418) that the author <> @RobertoGonzalez .  Do you want `Author` field to be "Aerolab" or you please?

**Comment by RobertoGonzalez** [comment]
@tomByrer Midnight was developed by my company, so we keep Aerolab as the formal author for everything. Thanks for adding it to jsDelivr!

**Comment by tomByrer** [comment]
> Thanks for adding it to jsDelivr!

Welcome!
Seems you have new PR since v1.0.0, so version in Releases & what is in the gh-pages are the same, but different code.  So, the larger CDN deployment procedures needs to be talked about.  There are 2 ways files end up on jsDelivr:
1. Automated (preferred) when you push to Releases, the jsDelivr bot sees the change & looks for the **minified** files.
   a. I or you can write a build script to make the minified file (I use [Gulp](https://github.com/terinjokes/gulp-uglify/))
   b. or you can add to the repo an [online minified](https://skalman.github.io/UglifyJS-online/) file by hand.
   Warning: both use UglifyJS, which need the `negate_iife : false` or else the IIFE will be gone.
2. I or someone else can upload to jsDelivr by hand.  I'll likely do it only the first time, then any time I need a new version up.  Sometimes others help, but it is random.

Let me know what you like best!

**Comment by sbehrends** [comment]
@tomByrer We just added the minified script and, for future builds, the gulp script.
