### ISSUE TITLE
Using Javascript reserved words

### ISSUE THREAD

**Issue by taunoha** [Aerolab/midnight.js#17]
It would be very helpful when you could replace javascript reserverd words from your code.  "class" is reserverd word and YUI compressor will throw an error and compression progess can't completed.

**Comment by RobertoGonzalez** [comment]
@taunoha Thanks for the tip! Since we are using uglify.js it went unnoticed. Do you want to throw in a PR with a fix?

**Comment by taunoha** [comment]
Why not :) 
It's a cool plugin and I would very much like to contribute.
