### ISSUE TITLE
Global scope pollution 

### ISSUE THREAD

**Issue by dfsq** [Aerolab/midnight.js#18]
There are several places where variable definitions lick into global scope. For example:

```
for( ix in sections ) { ... }
```

In the above example `ix` variable should be declared with `var` keyboard, otherwise `ix` becomes global variable.

**Comment by tomByrer** [comment]
*[leak](http://dictionary.reference.com/browse/leak)

This is lick ;)
![likcing contest pic](http://www.pbh2.com/wordpress/wp-content/uploads/2012/08/funniest-dog-gifs-dog-licking.gif)

I think the [IIFE protects from global leakage](http://gregfranko.com/blog/i-love-my-iife/) into the other scripts?  But perhaps a few extra `var` inside sub-functions can help with garbage collection...

**Comment by dfsq** [comment]
Lick :) 

No, even though wrapped into IIFE, assignment to undeclared variable will result into global variable. More over in strict mode there would be "ReferenceError: assignment to undeclared variable" error.
