### ISSUE TITLE
Cannot read property 'start' of undefined 

### ISSUE THREAD

**Issue by kimmobrunfeldt** [Aerolab/midnight.js#22]
I'm getting this error. This is the line that causes it: https://github.com/Aerolab/midnight.js/blob/gh-pages/midnight.jquery.src.js#L276

The actual reason is that when sections Array is looped with `for (x in array)` loop, it will take properties from prototype. The value of `ix` will be `toJSON` and the error is thrown. You should loop with `for (var i = 0; i < array.length; ++i)` instead or then check for hasOwnProperty.

**Comment by RobertoGonzalez** [comment]
@kimmobrunfeldt Thanks for the report! It should be fixed in the last commit, but let me know is there any further issues.
