### ISSUE TITLE
Miscalculation of header height in Chrome Beta

### ISSUE THREAD

**Issue by sbehrends** [Aerolab/midnight.js#28]
In the beta release channel of Google Chrome (41.0.2272.43 beta right now) the header is bigger than usual and uses almost half screen. I can guess that is some kind of miscalculation of the total height of the element.

**Comment by RobertoGonzalez** [comment]
@sbehrends This should be fixed on v1.1.0!

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
what will be fixxed?
