### ISSUE TITLE
Cuts header on middle in latest Chrome

### ISSUE THREAD

**Issue by jovehl** [Aerolab/midnight.js#30]
In Chrome Version 41.0.2272.76 (64-bit) the header gets cut in half for me. Both on my own site and on http://aerolab.github.io/midnight.js/. Is this a known issue?

**Comment by RobertoGonzalez** [comment]
@jovehl We found some issues on the Chrome Alphas, but we (incorrectly) assumed they wouldn't make it into the stable branch. I just fixed it on the new release (v1.1.0). Let me know if it works well.

Thanks for the report!
