### ISSUE TITLE
Overflow:hidden on parent hide the dropdown navbar

### ISSUE THREAD

**Issue by arifhussain353** [Aerolab/midnight.js#33]
Hi, 
I have one issue with this plugin.When ever i active plugin to my "mainNav" then my "dropDown"  show inside the "mainNav" tab. It because "midNight.js" add "overflow:hidden" to my "maiNav".Any solution for that ?

**Comment by RobertoGonzalez** [comment]
Midnight uses clipping via overflow:hidden to work, so there's not a straightforward workaround there.
However, the typical solution for the issue you're having is to use a dropdown plugin that gets attached directly to the body of the document (using a div with fixed positioning), so it's not affected by nav. I believe bootstrap does that.
A second (much dirtier) workaround is to create another div with position:fixed, placing it right on top of the nav and putting your dropdowns there.

**Comment by arifhussain353** [comment]
Ya thank you so much :)

**Comment by mhmdFawzy** [comment]
can you show me how to solve it and how to add the dropdown as i have the same problem

**Comment by RobertoGonzalez** [comment]
@Mohamedfawzyy You could try using an absolutely positioned dropdown for this. [Drop.js](http://github.hubspot.com/drop/docs/welcome/) would probably fit the bill (as well as the other plugins based on [Tether.js](http://tether.io/))

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
I can't fill in the application for AktionAktivAnarkistHansZwetsloot luciferia666@live.se 46736867135  Kyrkvagen 7 45431 Brastad Hans Zwetsloot 19680515=4934 J's.Midnight watch forking the intellectual...

Den 22 aug. 2017 14:29 skrev Mohamed Fawzy <notifications@github.com>:

can you show me how to solve it and how to add the dropdown as i have the same problem
