### ISSUE TITLE
Not working with jquery-lang-js

### ISSUE THREAD

**Issue by jdckl** [Aerolab/midnight.js#45]
Hello,
I am using Midnight on my website (development not production yet) and I am also using https://github.com/Irrelon/jquery-lang-js . There is an issue with these two things together, switching language changes the language only on the first (default) midnight navigation instance, every other midnight nav then contains default language. Any idea on how to fix this? I noticed midnight makes some nested divs that are clones of the original navigation element, the nested elements contain the lang attribute but seem to not change.. is there a way to call a jquery-lang init upon switching midnight headers? something like a callback on complete or something? That would probably fix it.

**Comment by RobertoGonzalez** [comment]
Looking at the source for jquery-lang it seems like it goes through the entire dom on .init() and sets the text where need. I'd try running jquery-lang after midnight is initialized (it creates all the custom elements at the start). After that it only adds a few inline styles to make the headers change places on scroll, but all other events should work normally.

**Comment by jdckl** [comment]
Bless you! Thanks. I had the hierarchy set out differently and I dont know why I didnt think of this haha.. thanks again :)

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
I got stuck ca24 months ago. I'm not kompetent enough. Could somebody help me?
