### ISSUE TITLE
Can't set the header background to transparant

### ISSUE THREAD

**Issue by cesarcor** [Aerolab/midnight.js#46]
Hi guys,

I was just wondering why can't I make my header element background transparent? e.g.

`.midnightHeader.testr{
  background-color: transparent;
 }
`

The code above will simply not work, the header remains the original color when I reach the testr section. 

Thanks and great plugin btw.

**Comment by RobertoGonzalez** [comment]
Hi @cesardowns 
Try styling just the **.midnightHeader.testr .midnightInner** class if you want to set a new background per section. The .midnightHeader class alone does some pre-clipping tasks and will often break if you try to style it directly.

A nicer workaround (so you get a bit more flexibility) is to create a container inside the nav, (like .real-header or something similar), set the background styles there, and leave .midnightHeader and .midnightInner unstyled.
