### ISSUE TITLE
Plugin fails when sections are hidden (display: none)

### ISSUE THREAD

**Issue by fabianhijlkema** [Aerolab/midnight.js#50]
This can be solved by using the following line:
`      this._$sections = $('[data-midnight]:visible');
`
Instead of:
`      this._$sections = $('[data-midnight]');
`

**Comment by RobertoGonzalez** [comment]
This should have been addressed by #47 . Thanks for the report!

**Comment by fabianhijlkema** [comment]
Yes. Thanks.
