### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by ValentinFertillet** [Aerolab/midnight.js#52]
Hey, 

I would like to use the midnight.js plugin on a website I am actually building. 
JQuery is installed via npm. Midnightjs too. I've imported both in my app.js file (jquery first). 
But I've got this error : Uncaught ReferenceError: jQuery is not defined. I do not understand why… any ideas ? 

Thanks !

<img width="635" alt="capture d ecran 2017-01-25 a 16 49 11" src="https://cloud.githubusercontent.com/assets/9061247/22297652/37bd3320-e31e-11e6-9658-2555a784e340.png">

<img width="879" alt="capture d ecran 2017-01-25 a 16 48 40" src="https://cloud.githubusercontent.com/assets/9061247/22297627/29785542-e31e-11e6-9e5b-bcc865959217.png">

**Comment by RobertoGonzalez** [comment]
Hi, midnight requires jQuery as a global, so I'm guessing that's why you are getting that error. You can try adding this before loading midnight:

`window.jQuery = require('jquery')`

While not exactly optimal, it may solve your issue.
