### ISSUE TITLE
Midnight header - drop down menus

### ISSUE THREAD

**Issue by wgstjf** [Aerolab/midnight.js#54]
Hi there,

We are using midnight to change the header logo and main nav as you scroll down the page.  Our issue is that the nav has dropdown menu items which are being hidden by the overflow:hidden applied to the wrapper element.  

Any clever thoughts on how to get around this issue?

Cheers,

Will

**Comment by RobertoGonzalez** [comment]
Hi @wgstjf,

The most direct way would be to use an absolutely-positioned dropdown that's a children of body. That way the dropdown is outside of the header's bounding box and won't be affected by it. 
Apart from that, the only issue would be to bind the click event to all the copies (either by binding to the container and filtering).

Cheers
