### ISSUE TITLE
What about SEO?

### ISSUE THREAD

**Issue by nicooprat** [Aerolab/midnight.js#61]
Crawlers now can execute JS, so isn't it problematic to duplicate the whole header and its links? Do anyone have any feedback about this?

**Comment by RobertoGonzalez** [comment]
@nicooprat It shouldn't cause any SEO-related issues. We've used it in a whole bunch of sites with no side effects, so it's pretty safe from that standpoint.

Cheers!

**Comment by nicooprat** [comment]
Glad to hear, do you have any examples I could check? Thanks.

**Comment by RobertoGonzalez** [comment]
@nicooprat I don't have any specific data I can share with you, but I've never seen any issues with SEO or received any bug reports saying that, so it should be pretty safe.
