### ISSUE TITLE
ES6 Module import

### ISSUE THREAD

**Issue by fstodulski** [Aerolab/midnight.js#62]
Hello.

I'm trying to import midnight.js into my file where i execute whole action.

I try
`import 'midnight.js/midnight.jquery.js';`
`import 'midnight.js` 
etc...

I use webpack to bundle my code.
`    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    }),
`

and getting error: `$(...).midnight is not a function`

node 6.11.5
yarn 1.0.1
midnight.js 1.1.1

**Comment by RobertoGonzalez** [comment]
Hi @Kamieniu, we don't support ES6 modules yet, but you should be able to get it to work by registering jQuery and $ as a global.

**Comment by sanderha** [comment]
@RobertoGonzalez As far as I can tell it does not work with jQuery or $ as global
