### ISSUE TITLE
Not firing check on AJAX page soft-refresh load.

### ISSUE THREAD

**Issue by wearelfb** [Aerolab/midnight.js#64]
I've got midnight working great, but it's not firing .midnight() again after an AJAX page load, even when calling the function again on complete. The elements that are being applied midnight aren't reloading on page change.

**Comment by RobertoGonzalez** [comment]
Hi @wearelfb! Try running `$('#yourHeader').midnight('refresh')`. 
It's an undocumented feature for that specific use case.

**Comment by wearelfb** [comment]
Sorry, forgot to respond to this -- Worked great. Thanks!
